import React from 'react';
import TaskContainer from '../tasks/TaskContainer';

function ListContainer( {taskList} ) {
    for (let i = 0; i < taskList.length; i++) {
        console.log(taskList[i].content);
        console.log(taskList[i].createTime);
        console.log(taskList[i].uid);
    }
    // each li in the ul is a TaskContainer
    // each task container has its unique key
    // key generated by crypto.randomUUID()
    return (
        <ul className='flex flex-col overflow-auto p-0
        w-4/5 divide-y divide-slate-500'>
            {taskList.map((task) => 
                <li key={task.uid}>
                    <TaskContainer task={task}/>
                </li>
            )}
        </ul>
    )
}




export default ListContainer;