import React from 'react';
import './css/ListContainer.css';
import TaskContainer from './components.task/TaskContainer';

function ListContainer( {taskList} ) {
    for (let i = 0; i < taskList.length; i++) {
        console.log(taskList[i].content);
        console.log(taskList[i].createTime);
        console.log(taskList[i].uid);
    }
    // each li in the ul is a TaskContainer
    // each task container has its unique key
    // key generated by crypto.randomUUID()
    return (
        <ul className='list-container'>
            {taskList.map((task) => 
                <li key={task.uid}>
                    <TaskContainer content={task.content}/>
                </li>
            )}
        </ul>
    )
}




export default ListContainer;